language: python

python:
  - 2.6
  - 2.7
  - pypy
  - 3.2
  - 3.3
  - 3.4

before_script:
    - sudo apt-get -y install php5
    - curl -sS https://getcomposer.org/installer | php
    - php composer.phar --prefer-source --dev --no-interaction update
    - sudo apt-get install php5-xdebug

script:
    - vendor/bin/phpunit -c tests/phpunit.xml
    - ./coveragit --silently
